### PR TITLE
Record OpenTelemetry spans

### LINKED ISSUE #52: Add OpenTelemetry support
Based on the OpenTelemetry work made in the client itself.

Here are the pull requests to backport:

- [x] https://github.com/elastic/elasticsearch-py/pull/2457
- [x] https://github.com/elastic/elasticsearch-py/pull/2466 
- [x] https://github.com/elastic/elasticsearch-py/pull/2470
- [x] https://github.com/elastic/elasticsearch-py/pull/2479
- [x] https://github.com/elastic/elasticsearch-py/pull/2482
- [x] https://github.com/elastic/elasticsearch-py/pull/2490
- [x] https://github.com/elastic/elasticsearch-py/pull/2491

Done with those pull requests:

 * https://github.com/elastic/elasticsearch-serverless-python/pull/69
 * https://github.com/elastic/elasticsearch-serverless-python/pull/70

### PR DESCRIPTION
**Pull request by pquentin**
Closes #52

Unlike #69 which mostly was code generation, this is the actual implementation.

Backports https://github.com/elastic/elasticsearch-py/pull/2466, https://github.com/elastic/elasticsearch-py/pull/2470, https://github.com/elastic/elasticsearch-py/pull/2479, https://github.com/elastic/elasticsearch-py/pull/2490 and https://github.com/elastic/elasticsearch-py/pull/2491

### CODE REVIEW

**Review by miguelgrinberg — APPROVED** [review]
Looks good, but note that the tests in the two test_otel.py files are being skipped. Should these run?

**Comment by pquentin** [comment]
They run on Buildkite, see the `test_otel` jobs.

**Comment by pquentin** [comment]
Closing/reopening to see if Read the Docs integration works.

**Comment by pquentin** [comment]
I also tested that well, it actually worked, and yes:

image

**Pull request merged**
